spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

external:
  ai:
    base-url: ${AI_URL}


---
spring:
  config:
    activate:
      on-profile: default
  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: aws
  jpa:
    hibernate:
      ddl-auto: validate

---
keys:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-milliseconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    places:
      key: ${GOOGLE_PLACES_API_KEY}
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    client-secret: ${KAKAO_CLIENT_SECRET}
